### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by joarc** [Grundamnen-SE/pesys#16]
Bör vi ha kvar shadows? Jag skulle säga det vore bättre utan då det betyda mindre kod, men även att det skulle se "renare" ut och istället för att ha en massa skuggor.

Åsikter/Förslag?

**Comment by ekner** [comment]
Jag vill ha kvar skuggorna. Vi kan dock kanske lösa kod-problemet. Jag kanske kan göra ett skript där man gör en html-fil som endast har en tabell, och så gör skriptet två tabeller av det med skuggor. Så varje gång man behöver ändra i tabell-layouten så kör man skriptet efter, som genererar den fil som ska användas.

**Comment by joarc** [comment]
Jag skulle säga att det vore smartare att göra så javascript "kopiera" den vanliga tabellen med alla ämnen och på så sätt generera den andra tabellen, det tror jag skulle vara enklast för både oss och användarna.

**Comment by ekner** [comment]
Ja, det var typ det jag tänkt, dock så ska inte allt innehåll i alla element läggas ut dubbelt, så inte riktigt så. Men jag har ett sätt att lösa detta på. Detta ska också göras på servern, för det kommer inte bli enklare för användarna att köra det på klientsidan, endast långsammare, för det kommer vara mycket skriptet ska gå igenom, och att generera det varje gång användaren går in på sidan är helt onödigt. Den enda nackdelen är att vi behöver köra det skriptet varje gång vi ändrar i index-filen, men det är inte ofta vi behöver göra det, så det är knappast något problem.

**Comment by joarc** [comment]
Det vore bättre ifall det inte kräver att vi behöver göra något för att det ska skapas.

**Comment by joarc** [comment]
Vi bör egentligen förbättra allt med tabellen så det tar mindre html/css och är effektivare.

**Comment by ekner** [comment]
Nu är detta fixat, se commit 5fb3c2c97c6afc66284b4c1a963203a081d3ddc0
